name: family_alert_app
description: "Family Alert App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  http: ^1.2.0

flutter:
  uses-material-design: true
